ARG IMAGE_FROM=jenkins/jenkins:lts-jdk11
FROM $IMAGE_FROM
ARG DEPENDENCY=.
ARG DKR_USER=jenkins

USER root

RUN apt-get -y update && \
    apt-get -y install apt-transport-https ca-certificates curl gnupg-agent software-properties-common && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") $(lsb_release -cs) stable" && \
    apt-get update && \
    apt-get -y install docker-ce docker-ce-cli containerd.io && \
    apt-get -y install cntlm && \
    apt-get -y install tinyproxy && \
    apt-get -y install sudo

#apt-get install sysv-rc-conf

RUN curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose && \
    ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

USER $DKR_USER
