echo "To test proxy:"
echo "  cd /misc"
echo "  javac JavaHttpsClient"
echo "  java -Djavax.net.debug=all -Djava.net.useSystemProxies=true JavaHttpsClient https://redhat.com/ 1"
echo "    or"
echo "  java -Dhttp.proxyHost=$DKR_PROXY_HOST -Dhttp.proxyPort=$DKR_PROXY_PORT -Dhttps.proxyHost=$DKR_PROXY_HOST -Dhttps.proxyPort=$DKR_PROXY_PORT JavaHttpsClient https://redhat.com/ 1"
echo "    or"
echo "  curl -L google.com"
echo "    or"
echo "  apt-get update (as root)"
